To avoid the CUDA error issue in RealESRGANer, add a sleep(0.1) measure as recommended.
File "realesrganer.py", in enhance
  output_img = output_img.data.squeeze().float().cpu().clamp_(0, 1).numpy()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.